### ISSUE TITLE
After update, various graphics artifacts

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#518]
[discord link:](https://discord.com/channels/340715434099605515/340717174907863051/1289256833747521657)

a glitch on "In Queue" button
![image](https://github.com/user-attachments/assets/5259908f-3645-4f8a-a200-6a78a46ca64b)

[discord link:](https://discord.com/channels/340715434099605515/581688710093996032/1289171255597072456)
"First two images are illustrating the issue with the net. The third shows the visible compression artifacts on the UI elements. The dark blue background also has some jpeg-like blocking slightly visible (shouldn't benefit from compression as it is just a single solid color "
![image](https://github.com/user-attachments/assets/eccf53d8-8a86-498b-bbd8-09a9f37b839e)
![image](https://github.com/user-attachments/assets/e21db7c3-2665-480d-9843-24395d6cc4db)
![image](https://github.com/user-attachments/assets/8608c3d9-3f04-44c5-adaa-95cb2b6690fc)

**Comment by carrotstien** [comment]
additional observations:
1. loading image has artifacts
2. laser pointing at menu has artifacts

**Comment by zezba9000** [comment]
Artifacts seem to be gone. Still good on ram.
Pushed to develop-memory

**Comment by OldFox-62** [comment]
since 349.11 some textures has heavy artefacts ...
change of graphics settings do not change the effect, so may be wrong compression?
Even the triangle, which indicates the player who serves next.
![fb0d04d63b5cc0ddaed24875f7d763cf](https://github.com/user-attachments/assets/8ae01c9c-7623-4ef4-a92c-6024d8c7dd87)
![e5099074d95c434d5b45269a862feef3](https://github.com/user-attachments/assets/f4760471-e71d-43cc-9c8b-94adf891a27c)
![3e27bf3158c0ef34062e3aa4b801bf32](https://github.com/user-attachments/assets/4c4f6135-173c-467a-9fbf-1945bc25a89d)
![ad80812168c063ce1677c3dc087bbdec](https://github.com/user-attachments/assets/911ab255-92fd-4428-8ff1-022ab3733128)

**Comment by zezba9000** [comment]
@OldFox-62 These should all be fixed in next build

**Comment by carrotstien** [comment]
SolidSlime — Today at 7:47 PM
I noticed the floor tiles in chalet looks quite blurry (only the floor tiles that are far away), when the render scale is 100% or 120%. 
It breaks the immersion when I do a pendulum serve and look towards those tiles, so now I have the rendering set to 200%.
Other than the floor tiles and the mountain, 120% actually looks good enough.

https://discord.com/channels/340715434099605515/581688710093996032/1291909606880186399

**Comment by rigopoui** [comment]
Since the latest update, the textures do look less compressed, but in the Tokyo environment it looks like they were downscaled or something. Many textures on trees/rocks/etc are just blurry blobs now vs to how it was before.

Also the artifact in the "In Queue" button is still present.

**Comment by carrotstien** [comment]
fixed the in queue button i believe
